// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CreateIdentityInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}
